### ISSUE TITLE
How to incorporate imagenet-subset (100 classes) into this framework?

### ISSUE THREAD

**Issue by zijGao** [Lsabetta/MIND#2]
After change codes with tiny-imagenet, It seems that the training on imagenet-subset is very slow? Will your release the code based on Imagenet-Subset?

**Comment by jbonato1** [comment]
Can you give us the specs of your dataset or a reference? i.e. num of images, images size, classes ecc

**Comment by Zi-Jian-Gao** [comment]
Thank you for your quick reply. It seems that I have solved it. It's caused by the incorrect load. If it works, I'd like to share it with you.

**Comment by jbonato1** [comment]
Great :)
